name: My first workflow
on: 
 push:
  branches:
   - master
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: Getting our code from github
     uses: actions/checkout@v3
   - name: Install dependencies
     run: npm ci
   - name: lint
     run: npm run lint
   - name: Test
     run: npm run test
   - name: upload artifacts
     uses: actions/upload-artifact@v3
     with:
      name: akshu
      path: dist
 build:
   needs: test
   runs-on: ubuntu-latest
   steps:
   - name: Getting our code from github
     uses: actions/checkout@v3
   - name: Install dependencies
     run: npm ci
   - name: build
     run: npm run build
   
    
   
   
   
  
