name: My first workflow
on: push
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: Getting our code from github
     uses: actions/checkout@v3
   - name: Install dependencies
     run: npm ci
   - name: lint
     run: npm run lint
   - name: Test
     run: npm run test
   - name: Build
     run: npm run Build
   
   
   
  
